### PR TITLE
feat: Add mRNA FASTA files

### PR DESCRIPTION
**Pull request by clarle**
This adds the mRNA sequences as [FASTA files](https://en.wikipedia.org/wiki/FASTA_format) into the repository, so they can be more easily consumed by bioinformatics tools such as [BioPython](https://biopython.org/).

### CODE REVIEW

**Comment by TennisGazelle** [comment]
To better your chances of getting merged, I recommend including documentation on how to generate the extra text files and at least a simple README with links to docs about this format and its standards.

**Review by deadly-platypus — APPROVED** [review]
I shouldn't be able to do this, but it lgtm

**Comment by nightlark** [comment]
> 
> 
> I shouldn't be able to do this, but it lgtm

Approving a PR doesn't really do much, someone with write access is still needed to merge PRs.

**Comment by clarle** [comment]
I'll add a small README explaining FASTA, but in terms of how I generated them, I just copied and pasted the text from the PDF into a file and then re-formatted them into the standard 70 character FASTA lines, haha.

**Comment by TennisGazelle** [comment]
That works lol :) (i.e. not a repo maintainer, must an open-source afficionado here.)

**Pull request closed without merging**
